spring:
  profiles:
    active: dev
  auth:
    jwt:
      secret: Jj5XQ0hjRy8=PV0=NXxXaEZmWCxRWCoveHM4WCN6aTkrRj81YQ==dGgtTGE2elhjLHgpJXtU
      expiration-mins: 15
      refresh-expiration-days: 1
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      show-sql: false
      ddl-auto: create-drop
---
spring:
  config:
    activate:
      on-profile: test
  application:
    name: Online code judgement system
  datasource:
    url: jdbc:h2:mem:ocjsysdb
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true